import java.util.*;
class Construct {

    // int x=100;
    // String y="Rang Birngangi";
//Instead of using instance variables, we will use constructor to initialize the variables.



    // int c;
    // String d;


    //BUT BUT BUT Encapsulation says that the var should be inaccessible from the outside world.
    // So we will make them private.

    private int c;
    private String d;




    public void press(){
        System.out.println("hello Construct");
    }

    public void press2(){
        System.out.println("hello press2");
    }

    public Construct() {
        // Constructor to initialize the object
        System.out.println("Construct created");
        c = 100; // default value
        d = "Rang Birngangi"; // default value
    }
    //below  GETTERS AND SETTERS WERE AUTOMATICALLY GENERATED BY THE IDE
    //TO DO THAT RIGHT - CLICK ANYWHERE OUTSIDE THE METHODS
    //THEN SELECT "SOURCE ACTIONS"\
    //THEN SELECT "GENERATE GETTERS AND SETTERS"
    //THEN SELECT THE VARIABLES YOU WANT TO GENERATE GETTERS AND SETTERS FOR
    //THEN CLICK ON "GENERATE"
    //THEN IT WILL GENERATE THE GETTERS AND SETTERS FOR YOU
    public int getC() {
        return c;
    }

    public void setC(int c) {
        this.c = c;
    }

    public String getD() {
        return d;
    }

    public void setD(String d) {
        this.d = d;
    }


    // Getters and Setters for encapsulation. R EFER THESE AFTER REDONG LINE  58-59

    
    
    // public int getC() {
    //     return c; // returns the value of c
    //      // returns the value of d

    // }

    // public String getD() {
    //     return d; // returns the value of d
    // }


    // public void setC(int c){
    //     // now there are 2 c here one that is outside in beginning of the class and one that is inside the method
    //     //i.e. one is local and one is instance variable
    //     //so we need to use 'this' keyword to refer to the instance variable
    //     this.c =c;
    //     //this.c is the instance variable and c is the local variable
    //     //so it sets the value of the instance variable c to the value of the local variable c that is recieved from the user

    //    }

    // public void setD(String d) {
    //     this.d = d; 
    // }

    //ABOVE WERE GETTER AND SETTERS THAT WERE MADE MAUALLY
    
    
}


class AdvancedConstruct extends Construct {

    public static void main(String[] args) {
        
        Scanner sc =new Scanner(System.in);


        Construct obj = new Construct();
        // The First Construct keyword is the class name,
        // then the obj is a reference variable that points to the object created by the constructor.
        //new keyword is used to create a new object of the Construct class.
        //Construct() is the constructor that initializes the object.it is used to call the constructor of the Construct class.
        //If the constructor is not defined, Java provides a default constructor that initializes the object with default values.
        obj.press();
        obj.press2();
        obj.getC();
        obj.getD();
        System.out.println("Value of c: " + obj.getC());
        System.out.println("Value of d: " + obj.getD());

        System.out.println("Enter a new value for c:");
        int newValue =sc.nextInt();
        obj.setC(newValue);
        sc.nextLine(); // Consume the newline character left by nextInt()
         // after each nextInt() and nextDouble() method, we need to call nextLine() to consume the newline character ie "\n" left in the buffer.
        System.out.println("Updated value of c: " + obj.getC());
        
        System.out.println("Enter a new value for d:");
        String newString = sc.nextLine();
        
        obj.setD(newString);
        System.out.println("Updated value of d: " + obj.getD());
        sc.close();
    }

        
        // obj.c=150;
        // obj.d="Rang Birngangi 2.0";
        // Above lines will give an error because c and d are private variables in the Construct class.

        //Now to make a soln for this and also follow encapsulation, we will use getters and setters.

    }

    

